#!/usr/bin/env python2

import sys

try:
    from ffmulticonverter import ffmulticonverter
except ImportError:
    # ffmulticonverter is not installed
    # load module from the same folder
    import ffmulticonverter

if __name__ == '__main__':
    ffmulticonverter.main(sys.argv[1:])

