# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/ffmulticonverter.ui'
#
# Created: Thu Nov 17 13:18:27 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FFMultiConverter(object):
    def setupUi(self, FFMultiConverter):
        FFMultiConverter.setObjectName(_fromUtf8("FFMultiConverter"))
        FFMultiConverter.setEnabled(True)
        FFMultiConverter.resize(612, 314)
        FFMultiConverter.setAcceptDrops(True)
        FFMultiConverter.setWindowTitle(QtGui.QApplication.translate("FFMultiConverter", "FF Multi Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(FFMultiConverter)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(QtGui.QApplication.translate("FFMultiConverter", "Select file:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.fromLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.fromLineEdit.setEnabled(True)
        self.fromLineEdit.setAcceptDrops(False)
        self.fromLineEdit.setFrame(True)
        self.fromLineEdit.setReadOnly(True)
        self.fromLineEdit.setObjectName(_fromUtf8("fromLineEdit"))
        self.horizontalLayout_4.addWidget(self.fromLineEdit)
        self.openToolButton = QtGui.QToolButton(self.centralwidget)
        self.openToolButton.setText(QtGui.QApplication.translate("FFMultiConverter", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.openToolButton.setObjectName(_fromUtf8("openToolButton"))
        self.horizontalLayout_4.addWidget(self.openToolButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.TabWidget = QtGui.QTabWidget(self.centralwidget)
        self.TabWidget.setToolTip(_fromUtf8(""))
        self.TabWidget.setObjectName(_fromUtf8("TabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.audFromComboBox = QtGui.QComboBox(self.tab)
        self.audFromComboBox.setObjectName(_fromUtf8("audFromComboBox"))
        self.gridLayout_4.addWidget(self.audFromComboBox, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.audToComboBox = QtGui.QComboBox(self.tab)
        self.audToComboBox.setObjectName(_fromUtf8("audToComboBox"))
        self.gridLayout_4.addWidget(self.audToComboBox, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.TabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.vidFromComboBox = QtGui.QComboBox(self.tab_2)
        self.vidFromComboBox.setObjectName(_fromUtf8("vidFromComboBox"))
        self.gridLayout_3.addWidget(self.vidFromComboBox, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.vidToComboBox = QtGui.QComboBox(self.tab_2)
        self.vidToComboBox.setObjectName(_fromUtf8("vidToComboBox"))
        self.gridLayout_3.addWidget(self.vidToComboBox, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.TabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.imgFromComboBox = QtGui.QComboBox(self.tab_3)
        self.imgFromComboBox.setObjectName(_fromUtf8("imgFromComboBox"))
        self.gridLayout_2.addWidget(self.imgFromComboBox, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.imgToComboBox = QtGui.QComboBox(self.tab_3)
        self.imgToComboBox.setObjectName(_fromUtf8("imgToComboBox"))
        self.gridLayout_2.addWidget(self.imgToComboBox, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.TabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.docFromComboBox = QtGui.QComboBox(self.tab_4)
        self.docFromComboBox.setObjectName(_fromUtf8("docFromComboBox"))
        self.gridLayout.addWidget(self.docFromComboBox, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.docToComboBox = QtGui.QComboBox(self.tab_4)
        self.docToComboBox.setObjectName(_fromUtf8("docToComboBox"))
        self.gridLayout.addWidget(self.docToComboBox, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.TabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.TabWidget)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.folderCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.folderCheckBox.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert all files  \n"
"in this folder", None, QtGui.QApplication.UnicodeUTF8))
        self.folderCheckBox.setObjectName(_fromUtf8("folderCheckBox"))
        self.horizontalLayout_2.addWidget(self.folderCheckBox)
        self.recursiveCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.recursiveCheckBox.setEnabled(True)
        self.recursiveCheckBox.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert files \n"
"recursively", None, QtGui.QApplication.UnicodeUTF8))
        self.recursiveCheckBox.setCheckable(True)
        self.recursiveCheckBox.setChecked(False)
        self.recursiveCheckBox.setObjectName(_fromUtf8("recursiveCheckBox"))
        self.horizontalLayout_2.addWidget(self.recursiveCheckBox)
        self.deleteCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.deleteCheckBox.setText(QtGui.QApplication.translate("FFMultiConverter", "Delete original", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCheckBox.setObjectName(_fromUtf8("deleteCheckBox"))
        self.horizontalLayout_2.addWidget(self.deleteCheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.typeRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.typeRadioButton.setEnabled(False)
        self.typeRadioButton.setText(QtGui.QApplication.translate("FFMultiConverter", "Same type", None, QtGui.QApplication.UnicodeUTF8))
        self.typeRadioButton.setObjectName(_fromUtf8("typeRadioButton"))
        self.horizontalLayout_3.addWidget(self.typeRadioButton)
        self.extRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.extRadioButton.setEnabled(False)
        self.extRadioButton.setText(QtGui.QApplication.translate("FFMultiConverter", "Same extension", None, QtGui.QApplication.UnicodeUTF8))
        self.extRadioButton.setObjectName(_fromUtf8("extRadioButton"))
        self.horizontalLayout_3.addWidget(self.extRadioButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.convertPushButton = QtGui.QPushButton(self.centralwidget)
        self.convertPushButton.setText(QtGui.QApplication.translate("FFMultiConverter", "&Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.convertPushButton.setObjectName(_fromUtf8("convertPushButton"))
        self.horizontalLayout.addWidget(self.convertPushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        FFMultiConverter.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FFMultiConverter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 612, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuKati = QtGui.QMenu(self.menubar)
        self.menuKati.setTitle(QtGui.QApplication.translate("FFMultiConverter", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuKati.setObjectName(_fromUtf8("menuKati"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setTitle(QtGui.QApplication.translate("FFMultiConverter", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setObjectName(_fromUtf8("menu"))
        FFMultiConverter.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(FFMultiConverter)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        FFMultiConverter.setStatusBar(self.statusBar)
        self.quitAction = QtGui.QAction(FFMultiConverter)
        self.quitAction.setText(QtGui.QApplication.translate("FFMultiConverter", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setShortcut(QtGui.QApplication.translate("FFMultiConverter", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.convertAction = QtGui.QAction(FFMultiConverter)
        self.convertAction.setText(QtGui.QApplication.translate("FFMultiConverter", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.convertAction.setToolTip(QtGui.QApplication.translate("FFMultiConverter", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.convertAction.setShortcut(QtGui.QApplication.translate("FFMultiConverter", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.convertAction.setObjectName(_fromUtf8("convertAction"))
        self.aboutAction = QtGui.QAction(FFMultiConverter)
        self.aboutAction.setText(QtGui.QApplication.translate("FFMultiConverter", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setShortcut(QtGui.QApplication.translate("FFMultiConverter", "Ctrl+?", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.menuKati.addAction(self.convertAction)
        self.menuKati.addSeparator()
        self.menuKati.addAction(self.quitAction)
        self.menu.addAction(self.aboutAction)
        self.menubar.addAction(self.menuKati.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.label.setBuddy(self.openToolButton)
        self.label_10.setBuddy(self.docFromComboBox)
        self.label_11.setBuddy(self.docToComboBox)
        self.label_8.setBuddy(self.docFromComboBox)
        self.label_9.setBuddy(self.docToComboBox)
        self.label_6.setBuddy(self.docFromComboBox)
        self.label_7.setBuddy(self.docToComboBox)
        self.label_4.setBuddy(self.docFromComboBox)
        self.label_5.setBuddy(self.docToComboBox)

        self.retranslateUi(FFMultiConverter)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FFMultiConverter)
        FFMultiConverter.setTabOrder(self.fromLineEdit, self.openToolButton)
        FFMultiConverter.setTabOrder(self.openToolButton, self.docFromComboBox)
        FFMultiConverter.setTabOrder(self.docFromComboBox, self.docToComboBox)
        FFMultiConverter.setTabOrder(self.docToComboBox, self.folderCheckBox)
        FFMultiConverter.setTabOrder(self.folderCheckBox, self.recursiveCheckBox)
        FFMultiConverter.setTabOrder(self.recursiveCheckBox, self.deleteCheckBox)
        FFMultiConverter.setTabOrder(self.deleteCheckBox, self.typeRadioButton)
        FFMultiConverter.setTabOrder(self.typeRadioButton, self.extRadioButton)
        FFMultiConverter.setTabOrder(self.extRadioButton, self.convertPushButton)

    def retranslateUi(self, FFMultiConverter):
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab), QtGui.QApplication.translate("FFMultiConverter", "Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("FFMultiConverter", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("FFMultiConverter", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("FFMultiConverter", "Documents", None, QtGui.QApplication.UnicodeUTF8))

