# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/ffmulticonverter.ui'
#
# Created: Sun Nov 13 00:27:35 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FFMultiConverter(object):
    def setupUi(self, FFMultiConverter):
        FFMultiConverter.setObjectName(_fromUtf8("FFMultiConverter"))
        FFMultiConverter.setEnabled(True)
        FFMultiConverter.resize(628, 295)
        FFMultiConverter.setAcceptDrops(True)
        FFMultiConverter.setWindowTitle(QtGui.QApplication.translate("FFMultiConverter", "FF Multi Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(FFMultiConverter)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(QtGui.QApplication.translate("FFMultiConverter", "Επιλογή αρχείου:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.fromLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.fromLineEdit.setEnabled(True)
        self.fromLineEdit.setAcceptDrops(False)
        self.fromLineEdit.setFrame(True)
        self.fromLineEdit.setReadOnly(True)
        self.fromLineEdit.setObjectName(_fromUtf8("fromLineEdit"))
        self.horizontalLayout_4.addWidget(self.fromLineEdit)
        self.openToolButton = QtGui.QToolButton(self.centralwidget)
        self.openToolButton.setText(QtGui.QApplication.translate("FFMultiConverter", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.openToolButton.setObjectName(_fromUtf8("openToolButton"))
        self.horizontalLayout_4.addWidget(self.openToolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setText(QtGui.QApplication.translate("FFMultiConverter", "Τύπος αρχείου:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.typeComboBox = QtGui.QComboBox(self.centralwidget)
        self.typeComboBox.setObjectName(_fromUtf8("typeComboBox"))
        self.gridLayout_3.addWidget(self.typeComboBox, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setText(QtGui.QApplication.translate("FFMultiConverter", "Μετατροπή από:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.fromComboBox = QtGui.QComboBox(self.centralwidget)
        self.fromComboBox.setObjectName(_fromUtf8("fromComboBox"))
        self.gridLayout_3.addWidget(self.fromComboBox, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setText(QtGui.QApplication.translate("FFMultiConverter", "Μετατροπή σε:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.toComboBox = QtGui.QComboBox(self.centralwidget)
        self.toComboBox.setObjectName(_fromUtf8("toComboBox"))
        self.gridLayout_3.addWidget(self.toComboBox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.folderCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.folderCheckBox.setText(QtGui.QApplication.translate("FFMultiConverter", "Μετατροπή όλων των\n"
"αρχείων στον φάκελο ", None, QtGui.QApplication.UnicodeUTF8))
        self.folderCheckBox.setObjectName(_fromUtf8("folderCheckBox"))
        self.horizontalLayout_2.addWidget(self.folderCheckBox)
        self.recursiveCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.recursiveCheckBox.setEnabled(True)
        self.recursiveCheckBox.setText(QtGui.QApplication.translate("FFMultiConverter", "Μετατροπή όλων των \n"
"αρχείων αναδρομικά", None, QtGui.QApplication.UnicodeUTF8))
        self.recursiveCheckBox.setCheckable(True)
        self.recursiveCheckBox.setChecked(False)
        self.recursiveCheckBox.setObjectName(_fromUtf8("recursiveCheckBox"))
        self.horizontalLayout_2.addWidget(self.recursiveCheckBox)
        self.deleteCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.deleteCheckBox.setText(QtGui.QApplication.translate("FFMultiConverter", "Διαγραφή \n"
"πρωτοτύπου", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCheckBox.setObjectName(_fromUtf8("deleteCheckBox"))
        self.horizontalLayout_2.addWidget(self.deleteCheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.typeRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.typeRadioButton.setEnabled(False)
        self.typeRadioButton.setText(QtGui.QApplication.translate("FFMultiConverter", "Ίδιου τύπου", None, QtGui.QApplication.UnicodeUTF8))
        self.typeRadioButton.setObjectName(_fromUtf8("typeRadioButton"))
        self.horizontalLayout_3.addWidget(self.typeRadioButton)
        self.extRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.extRadioButton.setEnabled(False)
        self.extRadioButton.setText(QtGui.QApplication.translate("FFMultiConverter", "Ίδιας κατάληξης", None, QtGui.QApplication.UnicodeUTF8))
        self.extRadioButton.setObjectName(_fromUtf8("extRadioButton"))
        self.horizontalLayout_3.addWidget(self.extRadioButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.convertPushButton = QtGui.QPushButton(self.centralwidget)
        self.convertPushButton.setText(QtGui.QApplication.translate("FFMultiConverter", "&Μετατροπή", None, QtGui.QApplication.UnicodeUTF8))
        self.convertPushButton.setObjectName(_fromUtf8("convertPushButton"))
        self.horizontalLayout.addWidget(self.convertPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        FFMultiConverter.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FFMultiConverter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 628, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuKati = QtGui.QMenu(self.menubar)
        self.menuKati.setTitle(QtGui.QApplication.translate("FFMultiConverter", "Αρχείο", None, QtGui.QApplication.UnicodeUTF8))
        self.menuKati.setObjectName(_fromUtf8("menuKati"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setTitle(QtGui.QApplication.translate("FFMultiConverter", "Βοήθεια", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setObjectName(_fromUtf8("menu"))
        FFMultiConverter.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(FFMultiConverter)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        FFMultiConverter.setStatusBar(self.statusBar)
        self.exitAction = QtGui.QAction(FFMultiConverter)
        self.exitAction.setText(QtGui.QApplication.translate("FFMultiConverter", "Έξοδος", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setShortcut(QtGui.QApplication.translate("FFMultiConverter", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.convertAction = QtGui.QAction(FFMultiConverter)
        self.convertAction.setText(QtGui.QApplication.translate("FFMultiConverter", "Μετατροπή", None, QtGui.QApplication.UnicodeUTF8))
        self.convertAction.setToolTip(QtGui.QApplication.translate("FFMultiConverter", "Μετατροπή", None, QtGui.QApplication.UnicodeUTF8))
        self.convertAction.setShortcut(QtGui.QApplication.translate("FFMultiConverter", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.convertAction.setObjectName(_fromUtf8("convertAction"))
        self.aboutAction = QtGui.QAction(FFMultiConverter)
        self.aboutAction.setText(QtGui.QApplication.translate("FFMultiConverter", "Περί", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setShortcut(QtGui.QApplication.translate("FFMultiConverter", "Ctrl+?", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.menuKati.addAction(self.convertAction)
        self.menuKati.addSeparator()
        self.menuKati.addAction(self.exitAction)
        self.menu.addAction(self.aboutAction)
        self.menubar.addAction(self.menuKati.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.label.setBuddy(self.openToolButton)
        self.label_3.setBuddy(self.typeComboBox)
        self.label_4.setBuddy(self.fromComboBox)
        self.label_5.setBuddy(self.toComboBox)

        self.retranslateUi(FFMultiConverter)
        QtCore.QMetaObject.connectSlotsByName(FFMultiConverter)
        FFMultiConverter.setTabOrder(self.fromLineEdit, self.openToolButton)
        FFMultiConverter.setTabOrder(self.openToolButton, self.typeComboBox)
        FFMultiConverter.setTabOrder(self.typeComboBox, self.fromComboBox)
        FFMultiConverter.setTabOrder(self.fromComboBox, self.toComboBox)
        FFMultiConverter.setTabOrder(self.toComboBox, self.folderCheckBox)
        FFMultiConverter.setTabOrder(self.folderCheckBox, self.recursiveCheckBox)
        FFMultiConverter.setTabOrder(self.recursiveCheckBox, self.deleteCheckBox)
        FFMultiConverter.setTabOrder(self.deleteCheckBox, self.typeRadioButton)
        FFMultiConverter.setTabOrder(self.typeRadioButton, self.extRadioButton)
        FFMultiConverter.setTabOrder(self.extRadioButton, self.convertPushButton)

    def retranslateUi(self, FFMultiConverter):
        pass

